"""Add new model

Revision ID: e3eb8c3e405d
Revises: f8261a2cc7f8
Create Date: 2023-12-10 01:54:58.351200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e3eb8c3e405d'
down_revision: Union[str, None] = 'f8261a2cc7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('title', sa.String(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('count', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_Product_id'), 'Product', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Product_id'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
